name: 'data_pipeline'
version: '1.0.0'
profile: 'data_pipeline'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  data_pipeline:
    staging:
      +materialized: view
      +snowflake_warehouse: dbt_wh
      +description: "Staging models for preliminary data transformations"
    marts:
      +materialized: view
      +snowflake_warehouse: dbt_wh
      +description: "Mart models for business insights and analytics"